frontend/package-lock.json, frontend/package.json
There are more high severity vulnerabilities but solving them implies a breaking change
=> build(deps): aplied 'npm audit fix' that solved critical vulnerabilities

frontend/src/customHooks/useBackdrop.js, frontend/src/modules/Workplace/DataSlice.jsx, frontend/src/modules/Workplace/index.jsx, frontend/src/modules/Workplace/main/MainPanel.jsx, frontend/src/modules/Workplace/useWorkspaceState.js, frontend/src/modules/Workspace-config/index.jsx, frontend/src/modules/Workspace-config/useLoadDoc.js
This commit includes:
1. Creating a new custom hook for backdrop
2. Removing isCategoryLoaded variable and replacing it with an existing curCategory variable
3. Adding a backdrop when getting positive elements
=> feat: created custom hook for backdrop

label_sleuth/app.py
=> cast category_id to int in delete category endpoint

label_sleuth/data_access/data_access_api.py, label_sleuth/data_access/file_based/file_based_data_access.py, label_sleuth/data_access/file_based/utils.py, label_sleuth/data_access/label_import_utils.py, label_sleuth/orchestrator/orchestrator_api.py
fix issue when no texts to import found
import runtime can be further improved
=> fix issue when importing texts with duplications and improve import runtime

label_sleuth/analysis_utils/labeling_reports.py, label_sleuth/data_access/data_access_api.py, label_sleuth/data_access/file_based/file_based_data_access.py, label_sleuth/data_access/label_import_utils.py, label_sleuth/models/core/catalog.py, label_sleuth/models/core/tools.py, label_sleuth/orchestrator/core/state_api/orchestrator_state_api.py, label_sleuth/orchestrator/orchestrator_api.py
fix bug when creating category after one of the categories was deleted + unrelated cosmetic changes
=> Create after delete

label_sleuth/models/hf_transformers.py
adding truncation to hf pipeline (https://stackoverflow.com/questions/67849833/how-to-truncate-input-in-the-huggingface-pipeline)
=> truncating text in hf pipeline

label_sleuth/app.py, label_sleuth/orchestrator/orchestrator_api.py, label_sleuth/test_app.py
Remove duplicate elements when retrieving all positive. Add support for retrieving all negatively labeled elements.
add a step to the end-to-end test.
=> Remove duplicates from labeled elements. add negative elements endpoint

frontend/src/const.js, frontend/src/modules/Workplace/DataSlice.jsx, frontend/src/modules/Workplace/index.jsx, frontend/src/modules/Workplace/information/WorkspaceInfo.jsx, frontend/src/modules/Workplace/main/Element.jsx, frontend/src/modules/Workplace/sidebar/EvaluationPanel.jsx, frontend/src/utils/utils.js
This PR improves the evaluation feature. It refactors the evaluation state. The last model version for which an evaluation has been done is stored, thus the user can be informed if the evaluation score is old. The following message is displayed in such case: 
`The precision of the 31st model is 75%. Current model is 33rd. Start a new precision evaluation to get the updated evaluation.`
=> Improve evaluation

label_sleuth/models/core/models_background_jobs_manager.py
=> do not add job to gpu thread pool if gpu is unavailable

label_sleuth/app.py, label_sleuth/models/core/model_api.py, label_sleuth/models/ensemble.py, label_sleuth/models/util/standalone_inference.py, label_sleuth/orchestrator/orchestrator_api.py
Enables exporting models to be used independently of the label sleuth frontend
=> [backend] Support model export

frontend/src/api/client.js, frontend/src/customHooks/useBackdrop.js, frontend/src/modules/Workplace/__tests__/test_workspaceInfo.js, frontend/src/modules/Workplace/information/FileTransferLabels/TransferLabelsDialog.jsx, frontend/src/modules/Workplace/information/WorkspaceInfo.jsx, frontend/src/modules/Workplace/redux/DataSlice.js, frontend/src/modules/Workspace-config/__tests__/test_worspaceConfig.js
This PR adds a button to the UI that lets the user download the last model version.
=> feat(frontend): add download model functionality

frontend/package-lock.json, frontend/package.json, frontend/src/api/client.js, frontend/src/customHooks/useLogOut.js, frontend/src/modules/Login/LoginSlice.js, frontend/src/modules/Workplace/redux/labelSlice.js, frontend/src/modules/Workspace-config/workspaceConfigSlice.js, frontend/src/setupTests.js
Fix issue that was causing authorization to not to work. Headers were being set uncorrectly.
=> Fix authentication headers issue

label_sleuth/app_utils.py, label_sleuth/orchestrator/orchestrator_api.py
for #237 
Handle the case where an error occurred before the training was started to enable exposing this info to the frontend
=> fix: better error handling before train started

label_sleuth/models/core/tools.py
The default spacy download method installs models via pip install, which is unsuitable for some deployment and packaging scenarios. For this reason we switch to downloading the spacy model archives manually
=> download spacy models directly and not via spacy cli

frontend/src/const.js, frontend/src/modules/Workplace/PanelManager.js, frontend/src/modules/Workplace/customHooks/useResize.js, frontend/src/modules/Workplace/information/WorkspaceInfo.jsx, frontend/src/modules/Workplace/main/MainPanel.jsx, frontend/src/modules/Workplace/main/MainPanel.module.css, frontend/src/modules/Workplace/sidebar/ContradictingLabelsPanel.jsx, frontend/src/modules/Workplace/sidebar/Element.jsx, frontend/src/modules/Workplace/upperbar/UpperBar.jsx, frontend/src/modules/Workplace/upperbar/UpperBar.module.css
This PR improves the way that the layout of the UI is managed. It refactors the code so that there is single point where the size of each component of the layout is (`const.js`). This changes are needed to achieve what is described on #240.
=> feat: Improve UI responsiveness and make right sidebar resizable

frontend/src/modules/Workplace/customHooks/useSidebarLabelingShorcuts.js, frontend/src/modules/Workplace/customHooks/useWorkspaceState.js, frontend/src/modules/Workplace/information/WorkspaceInfo.jsx, frontend/src/modules/Workplace/information/WorkspaceInfo.module.css, frontend/src/modules/Workplace/main/Element.jsx, frontend/src/modules/Workplace/sidebar/Element.jsx
This PR implements the following issues: #260, #258, #208 and #206.
=> Various small features

label_sleuth/analysis_utils/labeling_reports.py, label_sleuth/analysis_utils/test_labeling_reports.py, label_sleuth/data_access/core/data_structs.py
=> fix(backend): handle a single pos/neg in contradicting report

frontend/src/modules/Workplace/customHooks/useLabelState.js, frontend/src/modules/Workplace/main/Element.jsx, frontend/src/modules/Workplace/redux/DataSlice.js, frontend/src/modules/Workplace/redux/labelSlice.js, frontend/src/modules/Workplace/sidebar/Element.jsx
This PR implements and resolves #254.
Result: 
https://user-images.githubusercontent.com/22247838/200346437-a9b5956c-2832-4c7a-bf12-8bb26be11e21.mov
=> feat(frontend): add optimistic update for labeling actions

frontend/src/customHooks/usePanelPagination.js, frontend/src/modules/Workplace/customHooks/useWorkspaceState.js, frontend/src/modules/Workplace/main/customHooks/useMainPagination.js, frontend/src/modules/Workplace/redux/categorySlice.js, frontend/src/modules/Workplace/redux/modelSlice.js, frontend/src/modules/Workplace/sidebar/AllPositiveLabelsPanel.jsx, frontend/src/modules/Workplace/sidebar/ContradictingLabelsPanel.jsx, frontend/src/modules/Workplace/sidebar/LabelNextPanel.jsx, frontend/src/modules/Workplace/sidebar/PosPredictionsPanel.jsx, frontend/src/modules/Workplace/sidebar/SearchPanel.jsx, frontend/src/modules/Workplace/sidebar/SuspiciousLabelsPanel.jsx, frontend/src/modules/Workplace/sidebar/customHooks/useUpdateSearch.js
Improve elements fetching logic so that elements are retrieved only when needed and request are not duplicated.
=> feat: improve panel elements fetching logic

frontend/src/modules/Workplace/information/WorkspaceInfo.jsx, frontend/src/modules/Workplace/information/WorkspaceInfo.module.css, frontend/src/modules/Workplace/redux/DataSlice.js, label_sleuth/app.py, requirements.txt
=> Display system version on the UI

label_sleuth/models/hf_transformers.py
=> fix (backend): correct predictions for HFTransformers model

frontend/src/const.js, frontend/src/modules/Workplace/customHooks/useSidebarLabelingShorcuts.js
I accidentally comitted changes from other feature. I alredy reverted that commit and I am now merging the correct commit.
=> Fix: system is crashing because of a bad commit

frontend/src/components/Keyboard.jsx, frontend/src/modules/Workplace/__tests__/test_upperbar.js, frontend/src/modules/Workplace/customHooks/useSidebarLabelingShorcuts.js, frontend/src/modules/Workplace/index.jsx, frontend/src/modules/Workplace/main/MainPanel.jsx, frontend/src/modules/Workplace/main/ShortcutsModal.jsx, frontend/src/modules/Workplace/sidebar/Element.jsx, frontend/src/modules/Workplace/upperbar/UpperBar.jsx
=> feat: expose shortcuts information so users are aware of them

frontend/src/components/bars/upperBar/ButtonAppBar.jsx, frontend/src/components/dropdown/Dropdown.js, frontend/src/customHooks/useBackdrop.js, frontend/src/customHooks/usePanelPagination.js, frontend/src/error/useErrorHandler.js, frontend/src/modules/Workplace/__tests__/test_workspaceInfo.js, frontend/src/modules/Workplace/customHooks/useResize.js, frontend/src/modules/Workplace/index.jsx, frontend/src/modules/Workplace/information/Divider.jsx, frontend/src/modules/Workplace/information/DrawerHeader.jsx, frontend/src/modules/Workplace/information/ModelErrorAlert.jsx, frontend/src/modules/Workplace/information/ModelProgressBar/index.jsx, frontend/src/modules/Workplace/information/StatsContainer.jsx, frontend/src/modules/Workplace/information/TabPanel.jsx, frontend/src/modules/Workplace/information/customHooks/useCheckModelState.js, frontend/src/modules/Workplace/information/customHooks/useConfetti.js, frontend/src/modules/Workplace/information/customHooks/useNewModelNotifications.js, frontend/src/modules/Workplace/information/index.jsx, frontend/src/modules/Workplace/main/ShortcutsModal.jsx, frontend/src/modules/Workplace/redux/DataSlice.js, frontend/src/modules/Workplace/redux/labelSlice.js, frontend/src/modules/Workplace/sidebar/Element.jsx, frontend/src/modules/Workplace/sidebar/customHooks/useScrollElementIntoView.js, frontend/src/modules/Workplace/sidebar/customHooks/useUpdateSearch.js, frontend/src/modules/Workplace/tutorial/index.jsx, frontend/src/modules/Workplace/upperbar/CategoryCard.jsx, frontend/src/modules/Workplace/upperbar/Modal/EditCategoryModal.jsx, frontend/src/modules/Workspace-config/useLoadDoc.js, frontend/src/modules/Workspace-config/useNewWorkspace.js, frontend/src/utils/utils.js
This PRs makes code refactor for frontend code improvements, removes unused variables, improves react hooks dependencies.
=> Frontend refactors

frontend/src/components/pagination/ArrowsOnlyPagination.jsx, frontend/src/modules/Workplace/redux/panelsSlice.js, frontend/src/modules/Workplace/sidebar/PosPredictionsPanel.jsx, frontend/src/utils/utils.js, label_sleuth/app.py, label_sleuth/config.json, label_sleuth/data_access/data_access_api.py, label_sleuth/data_access/file_based/file_based_data_access.py, label_sleuth/orchestrator/orchestrator_api.py
=> Prediction batching

frontend/src/App.js, frontend/src/customHooks/useWorkspaceId.js, frontend/src/modules/Workplace/__tests__/test_workspaceInfo.js, frontend/src/modules/Workplace/customHooks/usePreloadDataset.js, frontend/src/modules/Workplace/index.jsx, frontend/src/modules/Workplace/information/index.jsx, frontend/src/modules/Workplace/redux/DataSlice.js, frontend/src/modules/Workplace/redux/categorySlice.js, frontend/src/modules/Workplace/redux/documentSlice.js, frontend/src/modules/Workplace/redux/evaluationSlice.js, frontend/src/modules/Workplace/redux/labelSlice.js, frontend/src/modules/Workplace/redux/modelSlice.js, frontend/src/modules/Workplace/redux/panelsSlice.js, frontend/src/modules/Workplace/upperbar/UpperBar.jsx, frontend/src/modules/Workspace-config/useExistWorkspace.js, frontend/src/setupTests.js, frontend/src/utils/utils.js, label_sleuth/app.py
Solves https://github.com/label-sleuth/label-sleuth/issues/301.
=> feat(frontend): preload dataset when workspace changes

label_sleuth/config.json
I accidentally pushed the config file used locally
=> fix: restore config

frontend/src/modules/Workplace/information/index.jsx
Callback function was incorrectly defined
=> fix: some workspace notifications are not being shown

frontend/src/App.js, frontend/src/customHooks/useWorkspaceId.js, frontend/src/modules/Workspace-config/index.jsx, frontend/src/modules/Workspace-config/useExistWorkspace.js, frontend/src/modules/Workspace-config/useNewWorkspace.js, frontend/src/modules/Workspace-config/workspaceConfigSlice.js, frontend/src/setupTests.js, frontend/src/utils/utils.js
=> fix: unexpected behavior due to shared state across tabs

frontend/src/modules/Workplace/customHooks/useFocusSidebarElement.js, frontend/src/modules/Workplace/sidebar/Element.jsx
=> fix: Avoid scrolling into view a sidebar element when labeling it

frontend/src/error/errorHandler.js
Closes https://github.com/label-sleuth/label-sleuth/issues/259.
=> feat: improve error notifications of 500 Server errors

label_sleuth/app.py
=> fix(backend): convert iteration_index to int

label_sleuth/data_access/data_access_api.py, label_sleuth/data_access/test_data_access_api.py
=> fix(backend) support dashes in element URI. add test

frontend/src/customHooks/useFocusSidebarElement.js, frontend/src/modules/Workplace/redux/panelsSlice.js, frontend/src/modules/Workplace/sidebar/Element.jsx
This PR disables scrolling into view a sidebar element on the sidebar panel when it is clicked.
=> Don't scroll sidebar element on click

frontend/src/App.js, frontend/src/components/version/SystemVersion.jsx, frontend/src/components/version/version.module.css, frontend/src/modules/Workplace/information/WorkspaceInfo.module.css, frontend/src/modules/Workplace/information/index.jsx, frontend/src/modules/Workplace/redux/index.js, frontend/src/modules/Workspace-config/index.jsx
=> feat: add system version to the menu page

frontend/src/modules/Workplace/sidebar/Element.jsx
=> fix: invalid regex in search makes the UI to crash

label_sleuth/models/core/model_policies.py
=> add policies for NB models

label_sleuth/models/core/catalog.py, label_sleuth/models/hf_transformers.py
adapt Hugging Face model to the model inheritance scheme, as discussed in #247
=> refactor HF-based models

label_sleuth/active_learning/core/active_learning_policies.py, label_sleuth/active_learning/policy/active_learning_changing_policy.py, label_sleuth/active_learning/policy/active_learning_policy.py, label_sleuth/active_learning/policy/static_active_learning_policy.py, label_sleuth/config.py, label_sleuth/orchestrator/orchestrator_api.py
i.e. start with strategy x and mode to strategy y
=> feat(backend): allow dynamic active active learning strategies

frontend/src/customHooks/useBackdrop.ts, frontend/src/customHooks/useFetchPanelElements.ts, frontend/src/customHooks/useFetchPrevNextDoc.ts, frontend/src/customHooks/useLabelState.ts, frontend/src/customHooks/useMainPagination.ts, frontend/src/customHooks/usePanelPagination.ts, frontend/src/customHooks/useWorkspaceState.ts, frontend/src/global.d.ts, frontend/src/modules/Workplace/main/MainPanel.tsx, frontend/src/modules/Workplace/redux/documentSlice.ts, frontend/src/modules/Workplace/redux/index.ts, frontend/src/modules/Workplace/redux/panelsSlice.ts
This PR changes the way a part of the document logic is managed. It mainly refactors some of the state variables. This change allows to change the backdrop logic in such a way that the backdrop doesn't blink when entering a workspace.
=> Improve doc logic

label_sleuth/models/core/catalog.py, label_sleuth/models/core/model_policies.py, label_sleuth/models/hf_transformers.py, label_sleuth/start_label_sleuth.py
Classifier based on [XLM-R](https://huggingface.co/xlm-roberta-base) with support for 100 languages (https://data.statmt.org/cc-100/)
=> feat(backend): multilingual XLM-R transformer model

frontend/src/customHooks/useLabelState.ts, frontend/src/global.d.ts, frontend/src/modules/Workplace/information/index.tsx, frontend/src/modules/Workplace/redux/index.ts, frontend/src/modules/Workplace/redux/labelSlice.ts, frontend/src/modules/Workplace/redux/panelsSlice.ts, frontend/src/utils/utils.ts
=> feat(UI): display weak labels for the current category

frontend/package-lock.json, frontend/package.json, frontend/src/components/Keyboard.tsx, frontend/src/components/pagination/ArrowsOnlyPagination.tsx, frontend/src/components/pagination/CustomPagination.tsx, frontend/src/customHooks/usePanelPagination.ts, frontend/src/customHooks/useResize.ts, frontend/src/customHooks/useSearchElement.ts, frontend/src/customHooks/useSidebarLabelingShorcuts.ts, frontend/src/customHooks/useTogglePanel.ts, frontend/src/customHooks/useUpdateSearch.ts, frontend/src/modules/Workplace/PanelManager.tsx, frontend/src/modules/Workplace/main/MainPanel.tsx, frontend/src/modules/Workplace/redux/evaluationSlice.ts, frontend/src/modules/Workplace/sidebar/AllPositiveLabelsPanel.tsx, frontend/src/modules/Workplace/sidebar/ContradictingLabelsPanel.tsx, frontend/src/modules/Workplace/sidebar/Element.tsx, frontend/src/modules/Workplace/sidebar/EvaluationPanel.tsx, frontend/src/modules/Workplace/sidebar/LabelNextPanel.tsx, frontend/src/modules/Workplace/sidebar/PosPredictionsPanel.tsx, frontend/src/modules/Workplace/sidebar/SearchPanel.tsx, frontend/src/modules/Workplace/sidebar/SuspiciousLabelsPanel.tsx, frontend/src/modules/Workplace/sidebar/components/commonComponents.tsx
Migrate the sidebar panel components.
Closes #363.
=> feat: typescript migration: sidebar panel

frontend/src/featureFlags/featureFlagsSlice.ts, frontend/src/global.d.ts, frontend/src/modules/Workplace/main/Element.module.css, frontend/src/modules/Workplace/main/Element.tsx, frontend/src/modules/Workplace/sidebar/Element.tsx, frontend/src/modules/Workplace/sidebar/index.module.css
=> feat: add right-to-left text support right-to-left laguages

frontend/src/customHooks/useExistWorkspace.ts, frontend/src/customHooks/useLoadDoc.ts, frontend/src/customHooks/useNewModelNotifications.ts, frontend/src/customHooks/useNewWorkspace.ts, frontend/src/customHooks/useNotifyUploadedLabels.ts, frontend/src/error/useNotifyError.ts, frontend/src/modules/Workplace/upperbar/Modal/CreateCategoryModal.jsx, frontend/src/modules/Workplace/upperbar/Modal/DeleteCategoryModal.jsx, frontend/src/modules/Workplace/upperbar/Modal/EditCategoryModal.jsx, frontend/src/modules/Workplace/upperbar/UpperBar.jsx, frontend/src/modules/Workspace-config/index.jsx, frontend/src/utils/notification.ts
=> feat: improve toast notification mechanism

frontend/src/const.ts, frontend/src/customHooks/useNotifyUploadedLabels.ts, frontend/src/modules/Workplace/redux/labelSlice.ts, frontend/src/utils/utils.ts
=> fix: Hebrew labeled data is incorrectly parsed on Excel

label_sleuth/config.py, label_sleuth/start_label_sleuth.py
=> fix(backend): properly parse boolean config parameters + improve args documentation

frontend/src/components/dropdown/Dropdown.tsx, frontend/src/modules/Workplace/upperbar/CategoryFormControl.tsx, frontend/src/modules/Workspace-config/ExistingWorkspaceForm.jsx, frontend/src/modules/Workspace-config/LoadDocumentForm.jsx, frontend/src/modules/Workspace-config/NewWorkspaceForm.jsx
=> feat: improve empty options dropdown

frontend/src/components/buttons/ButtonLight.jsx, frontend/src/modules/Workspace-config/WorspaceForm.tsx
#362 
Convert WorkspaceForm to .tsx 
Removed unused 'size' prop from ButtonLight
This is my first PR on this project. Please let me know any other changes you would like me to make. Thanks so much!
=> change WorkspaceForm to tsx and remove unused props from ButtonLight

label_sleuth/orchestrator/orchestrator_api.py
=> feat(backend): export each metadata field as a separate csv column

label_sleuth/models/ensemble.py
=> fix(backend): simpler loading of ensemble models + backward compatibility

frontend/src/const.ts, frontend/src/modules/Workplace/__tests__/test_upperbar.js, frontend/src/modules/Workplace/upperbar/Modal/CreateCategoryModal.tsx, frontend/src/modules/Workplace/upperbar/Modal/index.module.css, frontend/src/utils/test-utils.js
This PR adds a label to the create category modal 'Please select a meaningful name for your category.'.
=> feat: improve create category form

frontend/src/modules/Workplace/sidebar/SearchPanel.tsx
=> fix: search pagination doesn't work when there is no model

frontend/src/App.tsx, frontend/src/customHooks/useCheckSystemHealth.ts, label_sleuth/app.py
=> feat: inform the user if the system is down

frontend/src/const.ts, frontend/src/modules/Workplace/__tests__/test_upperbar.js, frontend/src/modules/Workplace/upperbar/Modal/CreateCategoryModal.tsx, frontend/src/modules/Workplace/upperbar/Modal/EditCategoryModal.tsx, label_sleuth/data_access/label_import_utils.py
Allow special characters and non-English characters (non-English class names)
=> feat(frontend): allow any character on class name, increase max length

frontend/src/const.ts, frontend/src/modules/Workplace/PanelManager.tsx, frontend/src/modules/Workplace/index.tsx, frontend/src/modules/Workplace/upperbar/CategoryCard.tsx, frontend/src/modules/Workplace/upperbar/index.tsx
=> feat: make sidebar panel wider and improve workspace resposiveness

label_sleuth/app.py, label_sleuth/app_utils.py, label_sleuth/config.json, label_sleuth/config.py, label_sleuth/config_for_tests.json
by default snippet is limited to 60 tokens
snippet may include query string if present
---
review by Alon
=> adding function to extract snippet from text

frontend/src/modules/Login/LoginForm.tsx, frontend/src/modules/Workplace/information/LabelCountTabs.tsx
=> Simplify logging in in using the keyboard

frontend/src/modules/Workplace/information/FileTransferLabels/index.tsx
=> feat: add indicator while the model is being loaded

label_sleuth/orchestrator/orchestrator_api.py
=> fix(backend): remove duplicates in contradiction panel

frontend/src/const.ts, frontend/src/customHooks/useExistWorkspace.ts, frontend/src/customHooks/useLoadDoc.ts, frontend/src/customHooks/useNewWorkspace.ts
=> feat: clarify indications for non provided fields in the workspace config page

frontend/src/components/element/LabelNonCurrentCatMenu.tsx, frontend/src/components/element/LabelingButtons.tsx, frontend/src/utils/utils.ts
=> Add other category labels badge

frontend/src/api/client.ts, frontend/src/modules/Workplace/redux/modelSlice.ts
This reverts commit 9c8f0dbaf1ed8cb90eb1e7c874b9b6a27d445008.
=> Revert "feat(frontend): stream model download"

frontend/src/api/client.ts, frontend/src/modules/Workplace/redux/index.ts, frontend/src/modules/Workplace/redux/modelSlice.ts
=> feat(frontend): stream model download

label_sleuth/app.py, label_sleuth/data_access/label_import_utils.py, label_sleuth/orchestrator/orchestrator_api.py
=> handle integer document ids in label import

frontend/src/components/dropdown/Dropdown.tsx, frontend/src/modules/Workplace/upperbar/CategoryFormControl.tsx
Resolves https://github.com/label-sleuth/label-sleuth/issues/511.
=> Category dropdown

frontend/src/App.tsx, frontend/src/modules/Login/index.tsx, frontend/src/modules/Workspace-config/__tests__/test_worspaceConfig.tsx, frontend/src/modules/Workspace-config/index.jsx, frontend/src/modules/index.ts, frontend/src/reportWebVitals.ts
Resolves https://github.com/label-sleuth/label-sleuth/issues/529.
=> Finish typescript migration

frontend/package-lock.json, frontend/src/components/dropdown/Dropdown.tsx, frontend/src/customHooks/useNotifyNewModelTraining.ts, frontend/src/customHooks/usePanelPagination.ts, frontend/src/modules/Workplace/index.tsx, frontend/src/modules/Workspace-config/LoadDocumentForm.tsx
=> Model training toast

label_sleuth/models/core/languages.py
=> feat: add Spanish support

frontend/src/customHooks/useLoadDoc.ts, frontend/src/featureFlags/featureFlagsSlice.ts, frontend/src/global.d.ts, label_sleuth/app.py, label_sleuth/config.json, label_sleuth/config.py, label_sleuth/config_for_tests.json, label_sleuth/data_access/data_access_api.py, label_sleuth/data_access/file_based/file_based_data_access.py, label_sleuth/orchestrator/orchestrator_api.py, label_sleuth/test_app.py
Resolves https://github.com/label-sleuth/label-sleuth/issues/553.
=> Add dataset size limit validation

frontend/src/const.ts, frontend/src/modules/Workplace/sidebar/EvaluationPanel.tsx, frontend/src/modules/Workplace/sidebar/SuspiciousLabelsPanel.tsx, frontend/src/modules/Workplace/sidebar/components/commonComponents.tsx
=> Improve evaluation panel messages

frontend/src/modules/Workplace/main/Element.module.css
Resolves https://github.com/label-sleuth/label-sleuth/issues/565.
=> Posive prediction UI

label_sleuth/app.py, label_sleuth/app_utils.py, label_sleuth/config_for_tests.json, label_sleuth/test_app.py
Resolves https://github.com/label-sleuth/label-sleuth/issues/571.
=> fix: search fails when using invalid regex

frontend/src/assets/sleuth_black.svg, frontend/src/assets/sleuth_blue.svg, frontend/src/components/element/MainElement.tsx, frontend/src/components/element/SidebarElement.tsx, frontend/src/components/element/index.module.css, frontend/src/const.ts, frontend/src/customHooks/useFocusNextPositivePrediction.ts, frontend/src/customHooks/useShorcuts.ts, frontend/src/global.d.ts, frontend/src/modules/Workplace/index.tsx, frontend/src/modules/Workplace/main/Element.module.css, frontend/src/modules/Workplace/main/MainPanel.module.css, frontend/src/modules/Workplace/main/MainPanel.tsx, frontend/src/modules/Workplace/main/NavigatePositivePredictions.tsx, frontend/src/modules/Workplace/main/ShortcutsModal.tsx, frontend/src/modules/Workplace/redux/panelsSlice.ts, frontend/src/modules/Workplace/sidebar/AllPositiveLabelsPanel.tsx, frontend/src/modules/Workplace/sidebar/LabelNextPanel.tsx, frontend/src/modules/Workplace/sidebar/SuspiciousLabelsPanel.tsx
In this PR the following changes are applied:
- Positive predictions focus and navigation: user can now navigage the positive predictions in the current document using buttons or shortcuts.
- New positive prediction elements design: the icon of LS is leveraged to denote positive predictions
- Sidebar elements redesign: the document name is now below the element's text
=> New sidebar elements and positive prediction design

frontend/src/components/element/SidebarElement.tsx, frontend/src/components/element/index.module.css, frontend/src/components/pagination/CustomPagination.tsx, frontend/src/modules/Workplace/PanelManager.tsx, frontend/src/modules/Workplace/main/MainPanel.module.css, frontend/src/modules/Workplace/main/MainPanel.tsx, frontend/src/modules/Workplace/sidebar/AllPositiveLabelsPanel.tsx, frontend/src/modules/Workplace/sidebar/ContradictingLabelsPanel.tsx, frontend/src/modules/Workplace/sidebar/EvaluationPanel.tsx, frontend/src/modules/Workplace/sidebar/LabelNextPanel.tsx, frontend/src/modules/Workplace/sidebar/PosPredictionsPanel.tsx, frontend/src/modules/Workplace/sidebar/SuspiciousLabelsPanel.tsx, frontend/src/modules/Workplace/sidebar/components/commonComponents.tsx, frontend/src/modules/Workplace/sidebar/index.module.css
Resolve https://github.com/label-sleuth/label-sleuth/issues/587 and https://github.com/label-sleuth/label-sleuth/issues/588.
=> Improve resposiveness

frontend/src/customHooks/useNewWorkspace.ts, frontend/src/global.d.ts, frontend/src/modules/Workspace-config/workspaceConfigSlice.ts, label_sleuth/app.py, label_sleuth/data_access/data_access_api.py, label_sleuth/data_access/file_based/file_based_data_access.py, label_sleuth/data_access/test_file_based_data_access.py, label_sleuth/orchestrator/core/state_api/orchestrator_state_api.py, label_sleuth/orchestrator/core/state_api/test_orchestrator_state_api.py, label_sleuth/orchestrator/orchestrator_api.py, label_sleuth/orchestrator/test_orchestrator_api.py, label_sleuth/test_app.py
=> Change create workspace parameter name

label_sleuth/app.py
=> User can't edit category desc or color without changing the category name

frontend/src/modules/Workplace/upperbar/Modal/EditOrCreateCategoryModal.tsx
=> User can bypass validation using shortcuts

frontend/src/customHooks/useLabelState.ts, frontend/src/modules/Workplace/redux/labelSlice.ts, label_sleuth/app.py, label_sleuth/app_utils.py, label_sleuth/orchestrator/core/state_api/orchestrator_state_api.py, label_sleuth/test_app.py
solves https://github.com/label-sleuth/label-sleuth/issues/609.
=> Rename set_element endpoint parameters and refactor

frontend/src/customHooks/useLabelState.ts, frontend/src/modules/Workplace/sidebar/ModelPredictionsPanel.tsx, frontend/src/modules/Workplace/sidebar/UserLabelsPanel.tsx
=> Add percentage to panels filter dropdown

frontend/src/modules/Workplace/sidebar/ModelPredictionsPanel.tsx
This happens only if there is already a trained model.
=> System crashes when creating a category

label_sleuth/models/core/model_api.py, label_sleuth/models/watsonx_models.py, label_sleuth/orchestrator/orchestrator_api.py
Don't trigger new iteration if category is edited and model dont use the category name
=> Mutliclass iteration triggering logic improvement
