label-sleuth/label-sleuth

frontend/src/modules/Workplace/main/customHooks/useElemStyles.js

This commit includes:
1. Remove unused else if, as the logic for getting the prediction has changed.
2. Adding an additional condition for the prediction's falsy value to match the values that are coming from the backend API, which are string values in case of false or true.

fix: bug in showing element in context

---

label_sleuth/orchestrator/orchestrator_api.py

When deleting a workspace and attempting to delete all models, check if the model has already been deleted.

fix: deleting all models of a category

---

label_sleuth/orchestrator/orchestrator_api.py

This resolves an edge case where if the model training is almost instantaneous, the system attempts to continue the iteration flow before an `Iteration` object has been created in the `orchestrator_state`.
resolves #198

prevent invoking the train callback before the iteration is created

---

frontend/src/modules/Workplace/information/WorkspaceInfo.jsx

This PR aims to clean up the code mentioned in Issue https://github.com/label-sleuth/label-sleuth/issues/207.
Regarding code: Erased unused tabStatus and setTabStatus from WorkspaceInfo.jsx
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as …

Enhancement: Erase unused tabStatus and setTabStatus

---

label_sleuth/models/core/model_api.py

for #237 
Windows has a limit of 260 characters for paths. Since the ensemble model name is a concatenation of 2 model ids, we sometimes exceed this limit. To avoid this, model_id was removed from the train_in_progress and train_complete file markers. Since these 2 files are in the model directory, using the id for them is redundant.

fix: reduce model path length

---

label_sleuth/app.py
label_sleuth/data_access/data_access_api.py
label_sleuth/orchestrator/orchestrator_api.py
label_sleuth/orchestrator/test_orchestrator_api.py

for #174 
This change adds a flag for the export_labels endpoint to export elements according to the elements that the system uses for training a model. For example, if the TrainingSetSelectionStrategy adds weakly labeled elements, these weakly labeled elements will also be exported.

feat: export according to the TrainingSetSelectionStrategy

---

label_sleuth/app.py
label_sleuth/data_access/data_access_api.py
label_sleuth/data_access/file_based/file_based_data_access.py
label_sleuth/data_access/file_based/utils.py
label_sleuth/data_access/label_import_utils.py
label_sleuth/orchestrator/orchestrator_api.py

for #219
interpret the `qry_string` parameter as just a string (not regex by default.
add an extra parameter `is_regex` to `orchestrator_api.query()`.
(this param is False for query(), but True in the context of `label_import_utils.get_element_group_by_texts()`)
DCO 1.1:
```
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open …
```

make search not-regex by default

---

label_sleuth/data_access/file_based/file_based_data_access.py

For counting the labels, create a copy of the labels object as the original object can change during the calculation

fix: create copy of labels for label counts

---

frontend/src/modules/Workplace/information/FileTransferLabels/TransferLabelsDialog.jsx

Refactor the code of the "Download model" modal so that the user can quickly see what they will find in the zip file. The following screenshot shows the changes that have been applied.

feat: add bullets to the "Download model" modal text

---

label_sleuth/data_access/label_import_utils.py

As the whitespaces are accepted category name characters, they shouldn't be replaced by whitespaces
Resolves #303.

fix: category name' whitespaces are replaced with underscore

---

frontend/src/modules/Workplace/sidebar/customHooks/useScrollElementIntoView.js

As part of a refactoring I introduce this regression bug.

fix: labeling a main element scrolls to top of the doc

---

frontend/src/modules/Workplace/index.tsx

This bug prevented users from scrolling on the worspace page. This bug seems to be caused by the z indez value of the backdrop that is used to dimmed the screen when something is loading.

Fix scrolling bug

---

frontend/src/global.d.ts
frontend/src/modules/Workplace/redux/modelSlice.ts
frontend/src/setupTests.js
frontend/src/utils/test-utils.js
label_sleuth/app.py
label_sleuth/test_app.py

This PR changes the wording of the information about the iterations of the current category from `model` to `iteration`. This PR also adds the new iteration status `PREPARING_DATA` to the list of training statuses that the frontend recognizes.

Add new model iteration

---

frontend/src/modules/Workplace/redux/modelSlice.ts

fix: 'Model is training' indicator is not shown when switching categories

---

frontend/src/components/combobox/ComboBoxWithInputText.jsx
frontend/src/customHooks/useLoadDoc.ts
frontend/src/customHooks/useNotifyUploadedLabels.ts
frontend/src/modules/Workspace-config/DeleteDatasetModal.tsx
frontend/src/modules/Workspace-config/DeleteWorkspaceModal.tsx
frontend/src/modules/Workspace-config/ExistingWorkspaceForm.jsx
frontend/src/modules/Workspace-config/LoadDocumentForm.jsx
frontend/src/modules/Workspace-config/index.jsx
frontend/src/modules/Workspace-config/workspaceConfigSlice.ts
frontend/src/utils/utils.ts
label_sleuth/app.py
label_sleuth/data_access/data_access_api.py
label_sleuth/data_access/file_based/file_based_data_access.py
label_sleuth/orchestrator/orchestrator_api.py

I've started working on [this issue](https://github.com/label-sleuth/label-sleuth/issues/409). First, to improve this first version:
- Improve the wording.
- Make the text that explain that some workspaces may be deleted too to call more the attention of the user. - Maybe we can add a subsequent modal after the first one in case workspaces are going to be deleted.
- Backend changes:
- add two endpoints: /datasets/<dataset_name>/used_by (GET) , which returns a list of the workspaces that use a particular dataset and /datasets/<dataset_name> (DELETE)
- add two method to the OrchestratorApi : get_workspaces_by_dataset_name()  and delete_dataset() , delete_dataset calls get_workspaces_by_dataset_name()  to delete workspaces if those are using the dataset that is going to be deleted and then …

Add the 'delete dataset' functionality

---

frontend/src/modules/Workplace/sidebar/LabelNextPanel.tsx

old text: "Label these elements next"
new text: "Labeling these elements next will be most effective at improving the model"

feat(frontend): change "Label Next" text to better describe the motivation for the user

---

frontend/src/App.tsx
frontend/src/components/combobox/ComboBoxWithInputText.tsx
frontend/src/const.ts
frontend/src/customHooks/useLoadDoc.ts
frontend/src/customHooks/useNewModelNotifications.ts
frontend/src/customHooks/useNewWorkspace.ts
frontend/src/customHooks/useNotifyNewModelTraining.ts
frontend/src/error/useNotifyError.tsx
frontend/src/modules/Workplace/information/FileTransferLabels/index.tsx
frontend/src/modules/Workplace/upperbar/Modal/CreateCategoryModal.tsx
frontend/src/modules/Workplace/upperbar/Modal/DeleteCategoryModal.tsx
frontend/src/modules/Workplace/upperbar/Modal/EditCategoryModal.tsx
frontend/src/modules/Workspace-config/DeleteDatasetModal.tsx
frontend/src/modules/Workspace-config/LoadDocumentForm.tsx
frontend/src/modules/Workspace-config/workspaceConfigSlice.ts
frontend/src/setupTests.ts
frontend/src/utils/notification.ts
label_sleuth/app.py

This PR improves the toast notification managment by:
- using the session storage to store which toasts are currently being displayed.
- use a naming convention for all toast ids: `[descriptive_name]_toast`.
- adapt tests.
- improve add documents toast notifications.
- set auto close to 5 seconds in the model is training toast notification.

Global toast messages

---

frontend/src/customHooks/useCheckModelState.ts
frontend/src/customHooks/useWorkspaceState.ts
frontend/src/featureFlags/featureFlagsSlice.ts
frontend/src/global.d.ts
frontend/src/modules/Workplace/information/LabelCountPanelMCMode.tsx
frontend/src/modules/Workplace/information/LabelingStatusMessage.tsx
frontend/src/modules/Workplace/information/index.tsx
frontend/src/modules/Workplace/upperbar/Modal/CategoriesMenu.tsx
label_sleuth/app.py

Adapt the logic behind deciding when to make /status endpoint calls.

Adapt labeling status message and model checks conditions

---

label_sleuth/data_access/file_based/file_based_data_access.py

Deleting a workspace fails if workspace's labels are not in memory.

Fix delete workspace

---

label_sleuth/app.py

When exporting the predictions for a multiclass workspace, the `predicted_label` is filled with the id of the category, which is no useful information for the user. This PR fills that field with the name of the category instead.

Export predictions with category names, not ids
